### ISSUE TITLE
 countryMap[country.name[].toLowerCase()] = country.name ;

### ISSUE THREAD

**Issue by Hitesh-VIT** [well-knits/country-count#2]
Can't convert array to lower String

**Comment by hems** [comment]
yeah this is definitely wrong, i ran into the same error.

A very ugly work around is to swap those two lines to:

````
    countryMap[country.name.common.toLowerCase()] = country.name.common
    countryMap[country.demonym.toLowerCase()] = country.name.common
 ````

but still there are more errors down the line. 😭

**Comment by ellell** [comment]
@Hitesh-VIT  @hems Hey, sorry about this, looks like a dependency changed structure without doing a major version. I'll look into fixing this, but also PRs are welcome! :)

**Comment by hems** [comment]
Hey @ellell thanks for getting back to us, i would love to PR but unfortunately got rekt by another project. 

Once i get back to this issue i might be able to help otherwise i'll happily test it ( sorry i know it sounds bad! ) !

thank you, peace

**Comment by kesla** [comment]
@hems @ellell Should be fixed.

**Comment by hems** [comment]
awesome, thanks!
